name: Test

on:
  pull_request:
  push:
    branch: master

jobs:
  test-ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node: [10, 12.16, 12, 13.6, 13.7, 13, 14]
    steps:
      - uses: actions/checkout@v2

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ matrix.os }}-node-${{ matrix.node }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ matrix.os }}-node-${{ matrix.node }}-

      - name: Install Dependencies
        run: npm i

      - name: Run test and coverage
        run: npm run test
